### ISSUE TITLE
molmod 1.4.8: Failing tests

### ISSUE THREAD

**Issue by robert-mijakovic** [molmod/molmod#45]
I'm using Python 3.8.6 and matplot lib 3.3.3.
GCC is 10.2.0.

The compilation is done with:
`export MATPLOTLIBRC=$PWD; echo 'backend: agg' > $MATPLOTLIBRC/matplotlibrc;python setup.py build_ext -i; nosetests -v`

While building MolMod 1.4.8 with Python 3.8.6, I get the following error:
```
======================================================================
ERROR: test_fingerprint_collisions (molmod.test.test_molecular_graphs.MolecularGraphTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/build/molmod/1.4.8/foss-2020b/molmod-1.4.8/molmod/test/test_molecular_graphs.py", line 387, in test_fingerprint_collisions
    g0 = Molecule.from_file(pkg_resources.resource_filename("../data/test/" + fn0))
TypeError: resource_filename() missing 1 required positional argument: 'resource_name'

======================================================================
FAIL: test_check_anagrad_full_prec (molmod.test.test_minimizer.MinimizerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/build/molmod/1.4.8/foss-2020b/molmod-1.4.8/molmod/test/test_minimizer.py", line 243, in test_check_anagrad_full_prec
    check_anagrad(prec_fun, x_init, 1e-5, 1e-4)
  File "/dev/shm/build/molmod/1.4.8/foss-2020b/molmod-1.4.8/molmod/minimizer.py", line 1608, in check_anagrad
    raise AssertionError("Error in the analytical gradient, component %i, got %s, should be about %s" % (i, ana_grad[i], num_grad_comp))
AssertionError: Error in the analytical gradient, component 1, got 0.3081499243346107, should be about -0.3733645133952023

======================================================================
FAIL: test_shortest_vector (molmod.test.test_unit_cells.UnitCellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/build/molmod/1.4.8/foss-2020b/molmod-1.4.8/molmod/test/test_unit_cells.py", line 175, in test_shortest_vector
    assert np.dot(change, r0) <= 0
AssertionError

----------------------------------------------------------------------
```

**Comment by maxim-masterov** [comment]
It seems that molmod switched from `nosetests` to `pytest`. Replacement  of `nosetests -v ` with `pytest -ra` should help.
